// same shim as the platform/ counterpart, with some crucial differences:
// - module name must be declare, inherit stack size of parent process.
// - module_start and module_stop are native PRX entrypoint callbacks.
#include <pspkernel.h>
#include <pspmoduleinfo.h>
#include <psyz/module.h>

// PRX modules must have a different name, or the OS will reject them.
// Module name is resolved in function(psyz_add_module MODULE_NAME)
#ifndef PSYZ_MODULE_NAME
#define PSYZ_MODULE_NAME "psyz_module"
#endif

PSP_MODULE_INFO(PSYZ_MODULE_NAME, 0, 1, 0);

#include <psputils.h>

// A PRX that fails to load HOST symbols can't use HOST logging API
#define LOG_ERROR(str) sceIoWrite(1, (str), sizeof(str));

enum {
    PSYZ_R_MIPS_32 = 2,
    PSYZ_R_MIPS_HI16 = 5,
    PSYZ_R_MIPS_LO16 = 6,
};

// custom table at .rodata.sceVarFixup generated by psp_module_abi.py
struct PsyzVarFixupEntry {
    // library-relative NID of the imported variable
    u32 nid;

    // real offset into the imported object, recovered at generation time
    u32 addend;

    // relative site offset, exactly as psp-readelf -r reports it
    u32 offset;

    // 2 = R_MIPS_32, 5 = R_MIPS_HI16, 6 = R_MIPS_LO16
    u32 type;
};

extern u32 g_sceVarFixupTable[];
extern u32 host_resolve_var(u32 nid);
extern char _ftext[];

static int ResolveHostGlobalVars(void) {
    struct PsyzVarFixupEntry* table =
        (struct PsyzVarFixupEntry*)g_sceVarFixupTable;
    int i;
    u32 lo = 0xFFFFFFFFu;
    u32 hi = 0;
    u32 lastNid = 0;
    u32 base = 0;

    for (i = 0; table[i].nid != 0 || table[i].offset != 0; i++) {
        u32 value;
        u32* site;

        if (i == 0 || table[i].nid != lastNid) {
            lastNid = table[i].nid;
            base = host_resolve_var(lastNid);
            if (!base) {
                LOG_ERROR(PSYZ_MODULE_NAME " failed to resolve nid");
                return -1;
            }
        }
        value = base + table[i].addend;
        site = (u32*)(_ftext + table[i].offset);

        switch (table[i].type) {
        case PSYZ_R_MIPS_32:
            *site = value;
            break;
        case PSYZ_R_MIPS_HI16:
            *site = (*site & 0xFFFF0000) | (((value + 0x8000) >> 16) & 0xFFFF);
            break;
        case PSYZ_R_MIPS_LO16:
            *site = (*site & 0xFFFF0000) | (value & 0xFFFF);
            break;
        default:
            LOG_ERROR(PSYZ_MODULE_NAME " failed to resolve symbol type");
            return -1;
        }

        if ((u32)site < lo) {
            lo = (u32)site;
        }
        if ((u32)site + 4 > hi) {
            hi = (u32)site + 4;
        }
    }
    if (hi > lo) {
        sceKernelDcacheWritebackRange((void*)lo, hi - lo);
        sceKernelIcacheInvalidateRange((void*)lo, hi - lo);
    }
    return 0;
}

int module_start(SceSize args, void* argp) {
    if (ResolveHostGlobalVars() < 0) {
        return -1;
    }
    Psyz_ModuleStart((argp && args >= sizeof(void*)) ? *(void**)argp : 0);
    return 0;
}

int module_stop(SceSize args, void* argp) {
    (void)args;
    (void)argp;
    Psyz_ModuleStop();
    return 0;
}
