#ifndef LIBSIO_H
#define LIBSIO_H

/* Driver Status bits (Table 16-2) */
#define SR_IRQ 0x200   /**< Interrupt on */
#define SR_CTS 0x100   /**< CTS is on */
#define SR_DSR 0x80    /**< DSR is on */
#define SR_FE 0x20     /**< Frame error occurs */
#define SR_OE 0x10     /**< Overrun error occurs */
#define SR_PERROR 0x08 /**< Parity error occurs */
#define SR_TXU 0x04    /**< No communications data */
#define SR_RXRDY 0x02  /**< Able to read communications data */
#define SR_TXRDY 0x01  /**< Able to write communications data */

/* Communications Mode bits (Table 16-4) */
#define MR_SB_01 0x40   /**< Stop bit length: 1 */
#define MR_SB_10 0x80   /**< Stop bit length: 1.5 */
#define MR_SB_11 0xC0   /**< Stop bit length: 2 */
#define MR_P_EVEN 0x20  /**< Parity: even */
#define MR_PEN 0x10     /**< Parity enabled */
#define MR_CHLEN_5 0x00 /**< Character length: 5 bit */
#define MR_CHLEN_6 0x04 /**< Character length: 6 bit */
#define MR_CHLEN_7 0x08 /**< Character length: 7 bit */
#define MR_CHLEN_8 0x0C /**< Character length: 8 bit */

/* Control Register bits (Table 16-5) */
#define CR_DSRIEN 0x1000 /**< DSR Interrupt Permission */
#define CR_RXIEN 0x800   /**< Receive Interrupt Permission */
#define CR_TXIEN 0x400   /**< Transmission Interrupt Permission */
#define CR_INTRST 0x40   /**< SIO1 Reset */
#define CR_RTS 0x20      /**< RTS is on */
#define CR_ERRRST 0x10   /**< Interrupt and error flag clear */
#define CR_RXEN 0x04     /**< Receive permission */
#define CR_DTR 0x02      /**< DTR is on */
#define CR_TXEN 0x01     /**< Transmission permission */

/**
 * @brief Initialize SIO driver
 *
 * Initializes the SIO driver at the communication speed baud.
 *
 * @param baud Communication speed (bps)
 * @return 1
 */
long AddSIO(int baud);

/**
 * @brief Delete SIO driver from kernel
 *
 * Deletes the SIO driver from the kernel.
 *
 * @return 1
 */
long DelSIO(void);

/**
 * @brief Set SIO interrupt callback function
 *
 * Defines func as the callback to be triggered when an interrupt has been
 * generated by the interrupt factors (CR_DSRIEN, CR_RXIEN, CR_TXIEN) set by
 * _sio_control(1,1, param). If func is 0, a callback is not generated. When an
 * interrupt is generated, the interrupt flag must be cleared using
 * _sio_control(2,1,0) or _sio_control(1,1,CR_ERRRST). The next SIO interrupt
 * isn't generated unless the interrupt flag is cleared.
 *
 * @param func Callback function
 * @return Address of previously installed callback function
 */
int Sio1Callback(void (*func)());

/**
 * @brief Issue SIO command
 *
 * SIO driver control and information acquisition.
 * Used in detailed communication with the PC and also when the user wishes to
 * suppress debugging data based on the standard output from the library, etc.
 *
 * Commands:
 * - cmd=0, arg=0: Returns driver status
 * - cmd=0, arg=1: Returns control line status
 * - cmd=0, arg=2: Returns communications mode
 * - cmd=0, arg=3: Returns communications speed (bps units)
 * - cmd=0, arg=4: Reads 1 byte
 * - cmd=1, arg=0: System reservation
 * - cmd=1, arg=1: Sets param value as control line status
 * - cmd=1, arg=2: Sets param value as communications mode
 * - cmd=1, arg=3: Sets param value as communications speed (bps units)
 * - cmd=1, arg=4: Writes 1 byte
 * - cmd=2, arg=0: Resets driver
 * - cmd=2, arg=1: Clears driver status error-related bits
 *
 * @param cmd Command
 * @param arg Subcommand
 * @param param Argument
 * @return Depends on command (see documentation Table 16-1)
 */
long _sio_control(unsigned long cmd, unsigned long arg, unsigned long param);

#endif
